name: ci

on:
  push:
    branches:
      - ci
  schedule:
    - cron: "*/3 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Check Status
        run: |
          git config --local user.email "1344299971@qq.com.com"
          git config --local user.name "kortin.zhou"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "ci: check status"
          git push
